runtime: nodejs20

env_variables:
  PORT: 3030
  DATABASE_URL: 'mysql://root:%5BSXt%2B%24UsHyzDLABB@10.36.240.3:3306/my-shoep'
  DEV_DATABASE_URL: 'mysql://root@localhost/shoep'
  JWT_SECRET_KEY: 'Shoep2024UdiPg'
  SOCRATA_API_TOKEN: '83wQK1qZRBx7zVCZ3LizzBklM'
  SOCRATA_API_URL: 'https://www.datos.gov.co/resource/wf53-j577.json'
  SELLER_ROLE_ID: 1
  CUSTOMER_ROLE_ID: 2
  MP_APP_ID: 6643569267880008
  MP_PUBLIC_KEY: 'TEST-5cd186b5-033a-42a8-8e04-4dcf438a3e07'
  MP_ACCESS_TOKEN: 'TEST-6643569267880008-122812-89f657de794d160939ad205b3cbb86f2-1046230477'
  MP_CLIENT_SECRET: 'Am5J6Ev4DythEGvfz4jrZeHRkUAg0mRo'
  MP_CLIENT_ID: 6643569267880008
  MP_OAUTH_URL: 'https://api.mercadopago.com/oauth/token'
